# https://taskfile.dev

version: '3'

vars:
  GREETING: "NRPC"

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  gen-all:
    desc: "go generate ./examples/alloptions"
    dir: ./examples/alloptions
    cmds:
      - echo "go generate ./examples/alloptions ..."
      - go generate 
      - echo "go generate ./examples/alloptions done."
    silent: true

  gen-hello:
    desc: "go generate ./examples/helloworld"
    dir: ./examples/helloworld/helloworld
    cmds:
      - echo "go generate ./examples/helloworld ..."
      - go generate 
      - echo "go generate ./examples/helloworld done."
    silent: true

  gen-metrics:
    desc: "go generate ./examples/metrics_helloworld"
    dir: ./examples/metrics_helloworld/helloworld
    cmds:
      - echo "go generate ./examples/metrics_helloworld ..."
      - go generate 
      - echo "go generate ./examples/metrics_helloworld done."
    silent: true

  install:
    desc: "install protoc-gen-nrpc[dev]"
    cmds:
      - task: assets
      - echo "protoc-gen-nrpc[dev] installing..."
      - go install ./protoc-gen-nrpc
      - echo "protoc-gen-nrpc[dev] installed."
    silent: true

  assets:
    cmds:
      - echo "assets building..."
      - go-bindata -o=protoc-gen-nrpc/bindata/bindata.go -ignore="\\.DS_Store|desktop.ini|README.md" -pkg=bindata -prefix=assets assets/... 
      - echo "assets build done."
    silent: true
    desc: "asset packaged"

  assets-debug:
    cmds:
      - echo "assets debug building..."
      - go-bindata -o=protoc-gen-nrpc/bindata/bindata.go -ignore="\\.DS_Store|desktop.ini|README.md" -pkg=bindata -prefix=assets -debug assets/... 
      - echo "assets debug build done."
    silent: true
    desc: "asset debug packaged"

  assets-fs:
    cmds:
      - echo "assets http.FileSystem building..."
      - go-bindata -o=protoc-gen-nrpc/bindata/bindata.go -ignore="\\.DS_Store|desktop.ini|README.md" -pkg=bindata -fs -prefix=assets assets/... 
      - echo "assets http.FileSystem build done."
    silent: true
    desc: "asset packaged"

  test:
    desc: "go test"
    cmds:
      - go test ./examples/alloptions
      - go test ./examples/helloworld/greeter_server
    silent: true

